### PR TITLE
owl-ode: add preliminary tests on method convergence

### PR DESCRIPTION
**Pull request by mseri**
This is just a perliminary test suite (failing for RK45 at the moment).

Signed-off-by: Marcello Seri <marcello.seri@gmail.com>

### CODE REVIEW

**Comment by mseri** [comment]
See also #5

**Comment by ghennequin** [comment]
Looks great to me!

**Review by tachukao — APPROVED** [review]
Looks great!  👍

**Comment by mseri** [comment]
Here we go. I’ll draft a release ASAP

**Pull request merged**
